template_path: documentdb.yaml
stack_name: agora-docdb-prod
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
  VpcName: "computevpc"
  MasterUser: "master"
  MasterPassword: !ssm /agora-prod/MongodbPassword
  DBInstanceClass: "db.r5.large"
