template_path: templates/beanstalk.yaml
stack_name: agora-staging
dependencies:
  - agoradb
parameters:
  AppDeployBucket: 'org-sagebionetworks-agora-deployment-agora-staging'
  AppEnv: 'staging'
  AppHealthcheckUrl: '/about'
  AutoScalingMaxSize: '4'
  AutoScalingMinSize: '2'
  SnsBounceNotificationEndpoint: 'agora-staging-bounce-notifications@sagebase.org'
  SnsNotificationEndpoint: 'agora-staging@sagebase.org'
  EbSolutionStackName: '64bit Amazon Linux 2018.03 v4.5.4 running Node.js'
  EC2InstanceType: 't2.small'
  EC2KeyName: 'toptal'
  MongodbHost: !stack_output_external agoradb-staging::PrimaryReplicaNodeIp
  MongodbAccessSecurityGroup: !stack_output_external agoradb-staging::MongoDBServerAccessSecurityGroup
