template_path: beanstalk.yaml
stack_name: agora-staging
dependencies:
  - staging/agoradb.yaml
parameters:
  AppDeployBucket: 'org-sagebionetworks-agora-deployment-agora-staging'
  AppEnv: 'staging'
  AppHealthcheckUrl: '/about'
  AutoScalingMaxSize: '4'
  AutoScalingMinSize: '2'
  EbHealthReportingSystem: 'enhanced'
  SnsBounceNotificationEndpoint: 'agora-staging-bounce-notifications@sagebase.org'
  SnsNotificationEndpoint: 'agora-staging@sagebase.org'
  EbSolutionStackName: '64bit Amazon Linux 2018.03 v4.13.0 running Node.js'
  EC2InstanceType: 't3.medium'
  EC2KeyName: 'agora-travis'
  MongodbHost: !stack_output_external agoradb-staging::PrimaryReplicaNodeIp
  MongodbAccessSecurityGroup: !stack_output_external agoradb-staging::MongoDBServerAccessSecurityGroup
