template_path: beanstalk-extras.yaml
stack_name: agora-staging-extras.yaml
dependencies:
  - staging/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:055273631518:loadbalancer/app/awseb-AWSEB-1JONRM5UT0GXI/5dc2d7ba9a4f4cda"
  CertificateArn: "arn:aws:acm:us-east-1:055273631518:certificate/412c0ea4-8123-48dd-b0af-608558cbb902"   # *.ampadportal.org
