template_path: beanstalk-extras.yaml
stack_name: agora-staging-extras
dependencies:
  - staging/agora.yaml
parameters:
  ListenerArn: "arn:aws:elasticloadbalancing:us-east-1:055273631518:listener/app/awseb-AWSEB-1JONRM5UT0GXI/5dc2d7ba9a4f4cda/37ca672c73a0eb53"
  CertificateArn: "arn:aws:acm:us-east-1:055273631518:certificate/412c0ea4-8123-48dd-b0af-608558cbb902"   # *.ampadportal.org
