# Provision a S3 static under maintenance website for agora
template_path: remote/managed-s3WebCloudfront.yaml
stack_name: agora-maintenance-website
parameters:
  # The department for this resource (i.e. CompOnc, SysBio, Platform, etc..)
  Department: "amp-ad"
  # The project for this resource (i.e. NTAP, BSMN, DREAM, etc..)
  Project: "SysBio"
  # The resource owner's email address
  OwnerEmail: "khai.do@sagebase.org"
  # Domain name for your website (sagebionetworks.org)
  DomainName: "ampadportal.org"
  # The sub domain name e.g. ('mysite' in mysite.sagebionetworks.org)
  SubDomainName: "maintenance"
  # The Amazon Resource Name (ARN) of an AWS Certificate Manager (ACM) certificate
  AcmCertificateArn: "arn:aws:acm:us-east-1:055273631518:certificate/412c0ea4-8123-48dd-b0af-608558cbb902"

hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/managed-s3WebCloudfront.yaml --create-dirs -o templates/remote/managed-s3WebCloudfront.yaml"
