# Provision an EC2 bastian host for agora
template_path: bastian2.yaml
stack_name: agora-bastian-docdb
parameters:
  # The Sage deparment for this resource
  Department: "SysBio"
  # The Sage project this resource will be used for
  Project: "amp-ad"
  # The resource owner
  OwnerEmail: "khai.do@sagebase.org"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t3.medium"
  # Name of an existing VPC subnet to run the instance in
  VpcSubnet: "PrivateSubnet"
  # Name of an existing EC2 KeyPair to enable SSH access to the instance
  KeyName: "agora-travis"
  # (Optional) ID of the base AMI (supported distros: AWS linux)
  AMIId: ami-003ed7eaef0321c8f     # AMI with mongo db tools
