template_path: templates/beanstalk.yaml
stack_name: agora-develop
dependencies:
  - agoradb
parameters:
  AppDeployBucket: 'org-sagebionetworks-agora-deployment-agora-develop'
  AppHealthcheckUrl: 'HTTP:80/about'
  AutoScalingMaxSize: '1'
  AutoScalingMinSize: '1'
  SnsBounceNotificationEndpoint: 'agora-develop-bounce-notifications@sagebase.org'
  SnsNotificationEndpoint: 'agora-develop@sagebase.org'
  EbSolutionStackName: '64bit Amazon Linux 2018.03 v4.5.4 running Node.js'
  EC2InstanceType: 't2.micro'
  MongodbHost: !stack_output_external agoradb-develop::PrimaryReplicaNodeIp
  NpmUseProduction: 'false'

