template_path: mongodb.yaml
stack_name: agoradb-develop
stack_tags:
  Department: "amp-ad"
  Project: "SysBio"
  OwnerEmail: "it@sagebase.org"
parameters:
  KeyPairName: 'agora-access'
  VpnCidr: !stack_output_external computevpc::VpnCidr
  VPC: !stack_output_external computevpc::VPCId
  PrimaryNodeSubnet: !stack_output_external computevpc::PrivateSubnet
  Secondary0NodeSubnet: !stack_output_external computevpc::PrivateSubnet1
  Secondary1NodeSubnet: !stack_output_external computevpc::PrivateSubnet2
  BastionSecurityGroupID: !stack_output_external computevpc::VpnSecurityGroup
  ClusterReplicaSetCount: '1'
  MongoDBAdminPassword: !ssm /agora-develop/MongodbPassword
  NodeInstanceType: 'm4.large'
  MongoDBVersion: "4.0"
