template_path: templates/mongodb.yaml
stack_name: agoradb-develop
parameters:
  KeyPairName: 'toptal'
  VPC: !stack_output_external computevpc::VPCId
  PrimaryNodeSubnet: !stack_output_external computevpc::PrivateSubnet
  Secondary0NodeSubnet: !stack_output_external computevpc::PrivateSubnet1
  Secondary1NodeSubnet: !stack_output_external computevpc::PrivateSubnet2
  BastionSecurityGroupID: !stack_output_external computevpc::VpnSecurityGroup
  ClusterReplicaSetCount: '1'
  MongoDBAdminPassword: !ssm /agora-develop/MongodbPassword
