template_path: beanstalk.yaml
stack_name: agora-develop
dependencies:
  - develop/agoradb.yaml
parameters:
  AppDeployBucket: 'org-sagebionetworks-agora-deployment-agora-develop'
  AppEnv: 'develop'
  AppHealthcheckUrl: '/about'
  AutoScalingMaxSize: '2'
  AutoScalingMinSize: '1'
  DISABLE_OPENCOLLECTIVE: 'true'
  SnsBounceNotificationEndpoint: 'agora-develop-bounce-notifications@sagebase.org'
  SnsNotificationEndpoint: 'agora-develop@sagebase.org'
  EbSolutionStackName: '64bit Amazon Linux 2018.03 v4.5.4 running Node.js'
  EC2InstanceType: 't2.medium'
  EC2KeyName: 'toptal'
  MongodbHost: !stack_output_external agoradb-develop::PrimaryReplicaNodeIp
  MongodbAccessSecurityGroup: !stack_output_external agoradb-develop::MongoDBServerAccessSecurityGroup
