AWSTemplateFormatVersion: 2010-09-09
Description: Essentials for Agora
Parameters:
  DNSDomainName:
    Description: DNS Domain name for app
    Type: String
    Default: 'ampadportal.org'
Resources:
  BeanstalkApplication:
    Type: 'AWS::ElasticBeanstalk::Application'
    Properties:
      ApplicationName: agora-ampad
#  HostedZone:
#    Type: "AWS::Route53::HostedZone"
#    Properties:
#      HostedZoneConfig:
#        Comment: "Agora hosted zone"
#      Name: !Ref DNSDomainName
#      VPCs:
#        -
#          VPCId: !ImportValue us-east-1-computevpc-VPCId
#          VPCRegion: !Ref AWS::Region

  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join
        - '.'
        - - '*'
          - !Ref DNSDomainName
      DomainValidationOptions:
        - DomainName: !Join
            - '.'
            - - '*'
              - !Ref DNSDomainName
          ValidationDomain: !Ref DNSDomainName
  KmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: !Join
        - '-'
        - - !Ref AWS::StackName
          - "KmsKey"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          -
            Sid: "Allow administration of the key"
            Effect: "Allow"
            Principal:
              AWS:
                - !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref AWS::AccountId
                    - ':root'
                - !ImportValue us-east-1-bootstrap-CfServiceRoleArn
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          -
            Sid: "Allow use of the key"
            Effect: "Allow"
            Principal:
              AWS:
                - !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref AWS::AccountId
                    - ':root'
                - !ImportValue us-east-1-bootstrap-CfServiceRoleArn
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Join
        - ''
        - - 'alias/'
          - !Ref AWS::StackName
          - '/KmsKey'
      TargetKeyId: !Ref KmsKey
Outputs:
  BeanstalkAppName:
    Value: !Ref BeanstalkApplication
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-BeanstalkAppName'
  HostedZoneId:
    Value: ZS9A6IHRRJXMS
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-HostedZoneId'
  SSLCertificate:
    Value: !Ref SSLCertificate
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-SSLCertificate'
  DNSDomainName:
    Value: !Ref DNSDomainName
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-DNSDomainName'
  KmsKey:
    Value: !Ref KmsKey
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-KmsKey'
  KmsKeyAlias:
    Value: !Ref KmsKeyAlias
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-KmsKeyAlias'
  KmsKeyArn:
    Value: !GetAtt KmsKey.Arn
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-KmsKeyArn'
