Description: Agora notifications
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  NotificationEndpoint:
    Type: String
    Description: Email address for notifications
Resources:
  SnsTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      Subscription:
        -
          Endpoint: !Ref NotificationEndpoint
          Protocol: "email"
  LogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 14
  ErrorMetricFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      LogGroupName: !Ref LogGroup
      FilterPattern: 'ERROR'
      MetricTransformations:
        -
          MetricValue: "1"
          MetricNamespace: !Sub '${AWS::StackName}/Errors'
          MetricName: !Sub '${AWS::StackName}-Error'
  ErrorAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmActions:
        - !Ref SnsTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      EvaluationPeriods: 1
      MetricName: !Ref ErrorMetricFilter
      Namespace: !Sub '${AWS::StackName}/Errors'
      Period: 3600
      Statistic: "Sum"
      Threshold: 4
      TreatMissingData: "notBreaching"
